# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
}:
{
  helium-aarch64 = {
    pname = "helium-aarch64";
    version = "0.5.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.5.7.1/helium-0.5.7.1-arm64.AppImage";
      sha256 = "sha256-w42trPZ8k8GDQfguVO+u7fAL4lTkYok77l23acABJzQ=";
    };
  };
  helium-x86_64 = {
    pname = "helium-x86_64";
    version = "0.5.7.1";
    src = fetchurl {
      url = "https://github.com/imputnet/helium-linux/releases/download/0.5.7.1/helium-0.5.7.1-x86_64.AppImage";
      sha256 = "sha256-A+fNcW7ujbeYqOb+gxzQ0p19J14csfFyok0RVRFxo60=";
    };
  };
}
