local opt = vim.opt
opt.icm = "split"
opt.scs = true
opt.ic = true
opt.nu = true
opt.rnu = true
opt.scl = "yes"
opt.shada = { "'10", "<0", "s10", "h" }
opt.swf = false
opt.fo:remove("o")
opt.wrap = true
opt.lbr = true
opt.ts = 4
opt.sw = 4
opt.more = false
opt.fdm = "manual"
opt.title = true
opt.titlestring = '%t%( %M%)%( (%{expand("%:~:h")})%)%a (nvim)'
opt.udf = true
